### ISSUE TITLE
Error of change the num_choice in mobilenetv1_bn_uniform_reset_bn.yml

### ISSUE THREAD

**Issue by chaunceywx** [changlin31/DS-Net#9]
I follow your suggestion to set the `num_choice` in mobilenetv1_bn_uniform_reset_bn.yml to 14, but get an expected error when I use `python -m torch.distributed.launch --nproc_per_node=8 train.py /PATH/TO/ImageNet -c ./configs/mobilenetv1_bn_uniform_reset_bn.yml.` 

08/25 10:15:57 AM Recalibrating BatchNorm statistics...
08/25 10:16:10 AM Finish recalibrating BatchNorm statistics.
08/25 10:16:19 AM Finish recalibrating BatchNorm statistics.
08/25 10:16:21 AM Test: [   0/0]  Mode: 0   Time: 0.344 (0.344)  Loss:  6.9204 (6.9204)  Prec@1:  0.0000 ( 0.0000)  Prec@5:  0.0000 ( 0.0000)  Flops: 132890408 (132890408)
08/25 10:16:22 AM Test: [   0/0]  Mode: 1   Time: 0.406 (0.406)  Loss:  6.9189 (6.9189)  Prec@1:  0.0000 ( 0.0000)  Prec@5:  0.0000 ( 0.0000)  Flops: 152917440 (152917440)
08/25 10:16:22 AM Test: [   0/0]  Mode: 2   Time: 0.381 (0.381)  Loss:  6.9187 (6.9187)  Prec@1:  0.0000 ( 0.0000)  Prec@5:  0.0000 ( 0.0000)  Flops: 175152224 (175152224)
08/25 10:16:23 AM Test: [   0/0]  Mode: 3   Time: 0.389 (0.389)  Loss:  6.9134 (6.9134)  Prec@1:  0.0000 ( 0.0000)  Prec@5:  0.0000 ( 0.0000)  Flops: 199594752 (199594752)
Traceback (most recent call last):
  File "train.py", line 658, in <module>
    main()
  File "train.py", line 635, in main
    eval_metrics.append(validate_slim(model,
  File "/home/chauncey/PycharmProjects/DS-Net-main/dyn_slim/apis/train_slim.py", line 215, in validate_slim
    output = model(input)
  File "/home/chauncey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chauncey/PycharmProjects/DS-Net-main/dyn_slim/models/dyn_slim_net.py", line 191, in forward
    x = self.forward_features(x)
  File "/home/chauncey/PycharmProjects/DS-Net-main/dyn_slim/models/dyn_slim_net.py", line 178, in forward_features
    x = stage(x)
  File "/home/chauncey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chauncey/PycharmProjects/DS-Net-main/dyn_slim/models/dyn_slim_stages.py", line 48, in forward
    x = self.first_block(x)
  File "/home/chauncey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chauncey/PycharmProjects/DS-Net-main/dyn_slim/models/dyn_slim_blocks.py", line 240, in forward
    x = self.conv_pw(x)
  File "/home/chauncey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chauncey/PycharmProjects/DS-Net-main/dyn_slim/models/dyn_slim_ops.py", line 94, in forward
    self.running_outc = self.out_channels_list[self.channel_choice]
IndexError: list index out of range

It looks like we should make some adjustment in other py files.

**Comment by changlin31** [comment]
We have now fixed the issue in recent commit 2d69459519efc92462f0fdc8c1f0ef9d22301769

This issue is caused by wrongly evaluation in the dynamic mode, which forces the routing space to the first 4 sub-networks to produce DS-MBNet-S:
https://github.com/changlin31/DS-Net/blob/2d69459519efc92462f0fdc8c1f0ef9d22301769/dyn_slim/apis/train_slim_gate.py#L223-L231
These lines is for controlling the routing space to reach different MAdds (see the supplementary of our paper) and should only be executed when arg `gate_train` is set to `true`.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/61453811/130775118-a551d0e0-82a8-4fb9-b1db-682423671573.png">

You can now reach different MAdds when training gate, by adjusting the `start_chn_idx` in `mobilenetv1_bn_uniform_gate.yml`:
https://github.com/changlin31/DS-Net/blob/2d69459519efc92462f0fdc8c1f0ef9d22301769/configs/mobilenetv1_bn_uniform_gate.yml#L39

**Comment by chaunceywx** [comment]
Thank you for your reply. Your code is a little difficult for me to understand, maybe I should speed more time to reading it.
